title    = "Hello World"
summary  = """\
The simplest possible Dispatchio pipeline: \
The Job class creates two jobs and a dependency between them.\
"""
tags       = ["PythonJob", "dependencies", "getting-started"]
order      = 1
show_files = ["my_work.py", "dispatchio.toml", "jobs.py", "run.py"]
