from __future__ import annotations

import shutil
from datetime import datetime, timedelta, timezone
from pathlib import Path
from uuid import uuid4

import typer

from dispatchio.cli import output
from dispatchio.cli.errors import CliUserError, handle_cli_errors

app = typer.Typer(
    help="Interactive sandbox for exploring Dispatchio CLI commands.",
    no_args_is_help=True,
)

_SANDBOX_DIR = ".dispatchio-sandbox"
_TOML_FILENAME = "dispatchio.toml"
_DB_FILENAME = "sandbox.db"

_TOML_CONTENT = """\
# Dispatchio sandbox configuration — auto-generated by `dispatchio sandbox init`

[dispatchio]
namespace = "sandbox"
log_level = "INFO"
default_cadence = "daily"

[dispatchio.state]
backend = "sqlalchemy"
connection_string = "sqlite:///{db_path}"

[dispatchio.receiver]
backend  = "filesystem"
drop_dir = ".dispatchio-sandbox/completions"
"""

_GUIDE = """\
[bold cyan]━━━  Dispatchio Sandbox  ━━━[/bold cyan]

The sandbox has been seeded with sample data under [bold].dispatchio-sandbox/[/bold].
A [bold]dispatchio.toml[/bold] has been written in this directory — the CLI will
pick it up automatically (or pass [bold]--context sandbox[/bold] if you registered it).

[bold]Scenario 1 — Inspect job history[/bold]
  dispatchio status
  dispatchio status --job ingest-daily
  dispatchio status --job ingest-daily --run-key 2024-01-15
  dispatchio ticks --limit 5

[bold]Scenario 2 — Explore a failed job[/bold]
  dispatchio status --job process-reports --run-key 2024-01-15

[bold]Scenario 3 — Dead-letter queue[/bold]
  dispatchio record list-dead-letters
  # Note the dead_letter_id, then:
  # dispatchio record resolve-dead-letter <id>

[bold]Scenario 4 — Retry a failed job[/bold]
  dispatchio retry list --filter requests
  dispatchio retry list --job process-reports --run-key 2024-01-15

[bold]Scenario 5 — Rename a job (registry)[/bold]
  # Suppose you rename "ingest-daily" to "ingest-v2" in code.
  # Run BEFORE changing the code:
  dispatchio job rename ingest-daily ingest-v2
  # After renaming back, or to simulate a remap (code renamed first):
  dispatchio job remap ingest-v2 ingest-daily

[bold]Scenario 6 — Record a manual event[/bold]
  dispatchio record set --name data-ready --run-key 2024-01-15

[dim]Reset the sandbox at any time with:[/dim]
  dispatchio sandbox reset
"""


def _sandbox_dir(target_dir: Path) -> Path:
    return target_dir / _SANDBOX_DIR


def _seed(db_path: str) -> None:
    from dispatchio.models import (
        Attempt,
        DeadLetter,
        DeadLetterReasonCode,
        DeadLetterSourceBackend,
        DeadLetterStatus,
        Event,
        RetryRequest,
        Status,
        TriggerType,
    )
    from dispatchio.state import SQLAlchemyStateStore

    store = SQLAlchemyStateStore(db_path, namespace="sandbox")

    now = datetime.now(tz=timezone.utc)

    def _dt(days_ago: float, hours: float = 0) -> datetime:
        return now - timedelta(days=days_ago, hours=hours)

    run_keys = ["2024-01-13", "2024-01-14", "2024-01-15"]

    # --- ingest-daily: healthy job with recent DONE attempts ---
    for i, rk in enumerate(run_keys):
        attempt = Attempt(
            namespace="sandbox",
            job_name="ingest-daily",
            run_key=rk,
            attempt=0,
            correlation_id=uuid4(),
            status=Status.DONE,
            submitted_at=_dt(2 - i, hours=1),
            started_at=_dt(2 - i, hours=0.9),
            completed_at=_dt(2 - i),
            trigger_type=TriggerType.SCHEDULED,
        )
        store.append_attempt(attempt)

    # --- process-reports: failed on the latest run key ---
    for i, rk in enumerate(run_keys[:2]):
        attempt = Attempt(
            namespace="sandbox",
            job_name="process-reports",
            run_key=rk,
            attempt=0,
            correlation_id=uuid4(),
            status=Status.DONE,
            submitted_at=_dt(2 - i, hours=2),
            started_at=_dt(2 - i, hours=1.8),
            completed_at=_dt(2 - i, hours=1),
            trigger_type=TriggerType.SCHEDULED,
        )
        store.append_attempt(attempt)

    failed_attempt = Attempt(
        namespace="sandbox",
        job_name="process-reports",
        run_key="2024-01-15",
        attempt=0,
        correlation_id=uuid4(),
        status=Status.ERROR,
        reason="Connection to upstream API timed out after 30s.",
        submitted_at=_dt(0, hours=3),
        started_at=_dt(0, hours=2.9),
        completed_at=_dt(0, hours=2),
        trigger_type=TriggerType.SCHEDULED,
    )
    store.append_attempt(failed_attempt)

    # --- export-summary: currently RUNNING ---
    running_attempt = Attempt(
        namespace="sandbox",
        job_name="export-summary",
        run_key="2024-01-15",
        attempt=0,
        correlation_id=uuid4(),
        status=Status.RUNNING,
        submitted_at=_dt(0, hours=1),
        started_at=_dt(0, hours=0.9),
        trigger_type=TriggerType.SCHEDULED,
    )
    store.append_attempt(running_attempt)

    # --- dead letter: unroutable completion event ---
    dead_letter = DeadLetter(
        occurred_at=_dt(0, hours=4),
        source_backend=DeadLetterSourceBackend.HTTP,
        reason_code=DeadLetterReasonCode.CORRELATION_FAILURE,
        reason_detail="No active attempt found for correlation_id in payload.",
        status=DeadLetterStatus.OPEN,
        namespace="sandbox",
        raw_payload={
            "job_name": "process-reports",
            "run_key": "2024-01-14",
            "status": "done",
            "unknown_correlation_id": str(uuid4()),
        },
    )
    store.append_dead_letter(dead_letter)

    # --- retry request for the failed process-reports run ---
    retry = RetryRequest(
        requested_at=_dt(0, hours=1.5),
        requested_by="sandbox-init",
        run_key="2024-01-15",
        requested_jobs=["process-reports"],
        selected_jobs=["process-reports"],
        assigned_attempt_by_job={"process-reports": 1},
        reason="Seeded retry from sandbox init",
    )
    store.append_retry_request(retry)

    # --- a recorded event (data dependency) ---
    event = Event(
        namespace="sandbox",
        name="upstream-data-ready",
        run_key="2024-01-15",
        occurred_at=_dt(0, hours=5),
    )
    store.set_event(event)


@app.command("init")
@handle_cli_errors
def init(
    target: str = typer.Argument(
        ".",
        help="Directory to create the sandbox in (default: current directory).",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite an existing sandbox.",
    ),
) -> None:
    """Create a sandbox with seeded data and print an interactive CLI guide.

    Creates a .dispatchio-sandbox/ directory and writes dispatchio.toml
    in the target directory so the CLI can auto-discover the sandbox.
    """
    from dispatchio.cli import output

    target_path = Path(target).resolve()
    sandbox_path = _sandbox_dir(target_path)
    toml_path = target_path / _TOML_FILENAME

    if sandbox_path.exists():
        if not force:
            raise CliUserError(
                f"Sandbox already exists at {sandbox_path}. "
                "Use --force to recreate it, or `dispatchio sandbox reset`."
            )
        shutil.rmtree(sandbox_path)

    sandbox_path.mkdir(parents=True)
    (sandbox_path / "completions").mkdir()

    db_path = sandbox_path / _DB_FILENAME
    toml_path.write_text(_TOML_CONTENT.format(db_path=db_path))

    _seed(f"sqlite:///{db_path}")

    output.console.print(
        f"[green]✓[/green] Sandbox created at [bold]{sandbox_path}[/bold]"
    )
    output.console.print(f"[green]✓[/green] Config written to [bold]{toml_path}[/bold]")
    output.console.print()
    guide()


@app.command("guide")
@handle_cli_errors
def guide() -> None:
    """Print an interactive CLI guide for the sandbox."""
    output.console.print(_GUIDE)


@app.command("reset")
@handle_cli_errors
def reset(
    target: str = typer.Argument(
        ".",
        help="Directory containing the sandbox (default: current directory).",
    ),
) -> None:
    """Wipe and re-seed the sandbox, restoring it to its initial state."""

    target_path = Path(target).resolve()
    sandbox_path = _sandbox_dir(target_path)

    if not sandbox_path.exists():
        raise CliUserError(
            f"No sandbox found at {sandbox_path}. Run `dispatchio sandbox init` first."
        )

    shutil.rmtree(sandbox_path)
    output.console.print(f"[yellow]↺[/yellow] Wiped [bold]{sandbox_path}[/bold]")

    toml_path = target_path / _TOML_FILENAME
    sandbox_path.mkdir(parents=True)
    (sandbox_path / "completions").mkdir()

    db_path = sandbox_path / _DB_FILENAME
    toml_path.write_text(_TOML_CONTENT.format(db_path=db_path))

    _seed(f"sqlite:///{db_path}")

    output.console.print(
        f"[green]✓[/green] Sandbox reset at [bold]{sandbox_path}[/bold]"
    )


@app.callback()
def callback() -> None:
    """Manage the Dispatchio interactive sandbox."""
